/**
 * This file is generated by Jux. For more information on how to use this file, visit https://jux.io/docs
 */

export const core = {
  color: {
    grays_0: {
      $value: 'violet',
      $description: '',
    },
    blues_100: {
      $value: 'rgba(230 242 250 / 100%)',
      $description: '',
    },
    blues_200: {
      $value: 'rgba(217 239 255 / 100%)',
      $description: '',
    },
    blues_500: {
      $value: 'rgba(5 143 242 / 100%)',
      $description: '',
    },
    grays_100: {
      $value: 'rgba(242 242 242 / 100%)',
      $description: '',
    },
    grays_150: {
      $value: 'rgba(235 235 235 / 100%)',
      $description: '',
    },
    grays_200: {
      $value: 'rgba(224 224 224 / 100%)',
      $description: '',
    },
    grays_300: {
      $value: 'rgba(189 189 189 / 100%)',
      $description: '',
    },
    grays_400: {
      $value: 'rgba(158 158 158 / 100%)',
      $description: '',
    },
    grays_500: {
      $value: 'rgba(97 97 97 / 100%)',
      $description: '',
    },
    grays_600: {
      $value: 'rgba(71 71 71 / 100%)',
      $description: '',
    },
    grays_650: {
      $value: 'rgba(48 48 48 / 100%)',
      $description: '',
    },
    grays_700: {
      $value: 'rgba(39 39 39 / 100%)',
      $description: '',
    },
    grays_750: {
      $value: 'rgba(33 33 33 / 100%)',
      $description: '',
    },
    grays_800: {
      $value: 'rgba(26 26 26 / 100%)',
      $description: '',
    },
    grays_900: {
      $value: 'rgba(20 20 20 / 100%)',
      $description: '',
    },
    pinks_200: {
      $value: 'rgba(255 214 218 / 100%)',
      $description: '',
    },
    pinks_300: {
      $value: 'rgba(255 153 163 / 100%)',
      $description: '',
    },
    pinks_500: {
      $value: 'rgba(255 92 108 / 100%)',
      $description: '',
    },
    grays_1000: {
      $value: 'rgba(0 0 0 / 100%)',
      $description: 'only used in banners',
    },
    purples_200: {
      $value: 'rgba(222 173 255 / 100%)',
      $description: '',
    },
    purples_300: {
      $value: 'rgba(198 112 255 / 100%)',
      $description: '',
    },
    purples_500: {
      $value: 'rgba(157 10 255 / 100%)',
      $description: '',
    },
    yellows_200: {
      $value: 'rgba(255 238 194 / 100%)',
      $description: '',
    },
    yellows_300: {
      $value: 'rgba(255 220 133 / 100%)',
      $description: '',
    },
    yellows_500: {
      $value: 'rgba(255 203 71 / 100%)',
      $description: '',
    },
    $description: 'Color tokens',
  },
  border: {
    $description: 'Border tokens',
  },
  dimension: {
    spacing_1: {
      $value: '0.25rem',
    },
    spacing_2: {
      $value: '0.5rem',
    },
    spacing_3: {
      $value: '0.75rem',
    },
    spacing_4: {
      $value: '1rem',
    },
    spacing_5: {
      $value: '1.25rem',
    },
    $description: 'Dimension tokens',
  },
  fontFamily: {
    $description: 'Font family tokens',
  },
  typography: {
    some_token: {
      $value: {
        fontWeight: 400,
      },
    },
    $description: 'Typography tokens',
  },
  $description: 'Core tokens',
};
