export interface GoogleFont {
  family:
    | 'Alegreya'
    | 'Alegreya Sans'
    | 'Archivo Narrow'
    | 'BioRhyme'
    | 'Cardo'
    | 'Chivo'
    | 'DM Sans'
    | 'Fira Sans'
    | 'IBM Plex Sans'
    | 'Inter'
    | 'Karla'
    | 'Lato'
    | 'Libre Baskerville'
    | 'Libre Franklin'
    | 'Lora'
    | 'Merriweather'
    | 'Neuton'
    | 'Open Sans'
    | 'PT Sans'
    | 'PT Serif'
    | 'Poppins'
    | 'Proza Libre'
    | 'Raleway'
    | 'Roboto'
    | 'Rubik'
    | 'Source Sans 3'
    | 'Space Mono'
    | 'Spectral'
    | 'Work Sans';
  variants: string[];
  subsets: string[];
}

export const googleFonts: GoogleFont[] = [
  {
    family: 'Alegreya',
    variants: [
      'regular',
      '500',
      '600',
      '700',
      '800',
      '900',
      'italic',
      '500italic',
      '600italic',
      '700italic',
      '800italic',
      '900italic',
    ],
    subsets: [
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'greek-ext',
      'latin',
      'latin-ext',
      'vietnamese',
    ],
  },
  {
    family: 'Alegreya Sans',
    variants: [
      '100',
      '100italic',
      '300',
      '300italic',
      'regular',
      'italic',
      '500',
      '500italic',
      '700',
      '700italic',
      '800',
      '800italic',
      '900',
      '900italic',
    ],
    subsets: [
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'greek-ext',
      'latin',
      'latin-ext',
      'vietnamese',
    ],
  },
  {
    family: 'Archivo Narrow',
    variants: [
      'regular',
      '500',
      '600',
      '700',
      'italic',
      '500italic',
      '600italic',
      '700italic',
    ],
    subsets: ['latin', 'latin-ext', 'vietnamese'],
  },
  {
    family: 'BioRhyme',
    variants: ['200', '300', 'regular', '500', '600', '700', '800'],
    subsets: ['latin', 'latin-ext'],
  },
  {
    family: 'Cardo',
    variants: ['regular', 'italic', '700'],
    subsets: ['greek', 'greek-ext', 'latin', 'latin-ext'],
  },
  {
    family: 'Chivo',
    variants: [
      '100',
      '200',
      '300',
      'regular',
      '500',
      '600',
      '700',
      '800',
      '900',
      '100italic',
      '200italic',
      '300italic',
      'italic',
      '500italic',
      '600italic',
      '700italic',
      '800italic',
      '900italic',
    ],
    subsets: ['latin', 'latin-ext', 'vietnamese'],
  },
  {
    family: 'DM Sans',
    variants: [
      '100',
      '200',
      '300',
      'regular',
      '500',
      '600',
      '700',
      '800',
      '900',
      '100italic',
      '200italic',
      '300italic',
      'italic',
      '500italic',
      '600italic',
      '700italic',
      '800italic',
      '900italic',
    ],
    subsets: ['latin', 'latin-ext'],
  },
  {
    family: 'Fira Sans',
    variants: [
      '100',
      '100italic',
      '200',
      '200italic',
      '300',
      '300italic',
      'regular',
      'italic',
      '500',
      '500italic',
      '600',
      '600italic',
      '700',
      '700italic',
      '800',
      '800italic',
      '900',
      '900italic',
    ],
    subsets: [
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'greek-ext',
      'latin',
      'latin-ext',
      'vietnamese',
    ],
  },
  {
    family: 'IBM Plex Sans',
    variants: [
      '100',
      '100italic',
      '200',
      '200italic',
      '300',
      '300italic',
      'regular',
      'italic',
      '500',
      '500italic',
      '600',
      '600italic',
      '700',
      '700italic',
    ],
    subsets: [
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'latin',
      'latin-ext',
      'vietnamese',
    ],
  },
  {
    family: 'Inter',
    variants: [
      '100',
      '200',
      '300',
      'regular',
      '500',
      '600',
      '700',
      '800',
      '900',
      '100italic',
      '200italic',
      '300italic',
      'italic',
      '500italic',
      '600italic',
      '700italic',
      '800italic',
      '900italic',
    ],
    subsets: [
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'greek-ext',
      'latin',
      'latin-ext',
      'vietnamese',
    ],
  },
  {
    family: 'Karla',
    variants: [
      '200',
      '300',
      'regular',
      '500',
      '600',
      '700',
      '800',
      '200italic',
      '300italic',
      'italic',
      '500italic',
      '600italic',
      '700italic',
      '800italic',
    ],
    subsets: ['latin', 'latin-ext'],
  },
  {
    family: 'Lato',
    variants: [
      '100',
      '100italic',
      '300',
      '300italic',
      'regular',
      'italic',
      '700',
      '700italic',
      '900',
      '900italic',
    ],
    subsets: ['latin', 'latin-ext'],
  },
  {
    family: 'Libre Baskerville',
    variants: ['regular', 'italic', '700'],
    subsets: ['latin', 'latin-ext'],
  },
  {
    family: 'Libre Franklin',
    variants: [
      '100',
      '200',
      '300',
      'regular',
      '500',
      '600',
      '700',
      '800',
      '900',
      '100italic',
      '200italic',
      '300italic',
      'italic',
      '500italic',
      '600italic',
      '700italic',
      '800italic',
      '900italic',
    ],
    subsets: ['latin', 'latin-ext', 'vietnamese'],
  },
  {
    family: 'Lora',
    variants: [
      'regular',
      '500',
      '600',
      '700',
      'italic',
      '500italic',
      '600italic',
      '700italic',
    ],
    subsets: [
      'cyrillic',
      'cyrillic-ext',
      'latin',
      'latin-ext',
      'math',
      'symbols',
      'vietnamese',
    ],
  },
  {
    family: 'Merriweather',
    variants: [
      '300',
      '300italic',
      'regular',
      'italic',
      '700',
      '700italic',
      '900',
      '900italic',
    ],
    subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext', 'vietnamese'],
  },
  {
    family: 'Neuton',
    variants: ['200', '300', 'regular', 'italic', '700', '800'],
    subsets: ['latin', 'latin-ext'],
  },
  {
    family: 'Open Sans',
    variants: [
      '300',
      'regular',
      '500',
      '600',
      '700',
      '800',
      '300italic',
      'italic',
      '500italic',
      '600italic',
      '700italic',
      '800italic',
    ],
    subsets: [
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'greek-ext',
      'hebrew',
      'latin',
      'latin-ext',
      'math',
      'symbols',
      'vietnamese',
    ],
  },
  {
    family: 'PT Sans',
    variants: ['regular', 'italic', '700', '700italic'],
    subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext'],
  },
  {
    family: 'PT Serif',
    variants: ['regular', 'italic', '700', '700italic'],
    subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext'],
  },
  {
    family: 'Poppins',
    variants: [
      '100',
      '100italic',
      '200',
      '200italic',
      '300',
      '300italic',
      'regular',
      'italic',
      '500',
      '500italic',
      '600',
      '600italic',
      '700',
      '700italic',
      '800',
      '800italic',
      '900',
      '900italic',
    ],
    subsets: ['latin', 'latin-ext'],
  },
  {
    family: 'Proza Libre',
    variants: [
      'regular',
      'italic',
      '500',
      '500italic',
      '600',
      '600italic',
      '700',
      '700italic',
      '800',
      '800italic',
    ],
    subsets: ['latin', 'latin-ext'],
  },
  {
    family: 'Raleway',
    variants: [
      '100',
      '200',
      '300',
      'regular',
      '500',
      '600',
      '700',
      '800',
      '900',
      '100italic',
      '200italic',
      '300italic',
      'italic',
      '500italic',
      '600italic',
      '700italic',
      '800italic',
      '900italic',
    ],
    subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext', 'vietnamese'],
  },
  {
    family: 'Roboto',
    variants: [
      '100',
      '100italic',
      '300',
      '300italic',
      'regular',
      'italic',
      '500',
      '500italic',
      '700',
      '700italic',
      '900',
      '900italic',
    ],
    subsets: [
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'greek-ext',
      'latin',
      'latin-ext',
      'vietnamese',
    ],
  },
  {
    family: 'Rubik',
    variants: [
      '300',
      'regular',
      '500',
      '600',
      '700',
      '800',
      '900',
      '300italic',
      'italic',
      '500italic',
      '600italic',
      '700italic',
      '800italic',
      '900italic',
    ],
    subsets: [
      'arabic',
      'cyrillic',
      'cyrillic-ext',
      'hebrew',
      'latin',
      'latin-ext',
    ],
  },
  {
    family: 'Source Sans 3',
    variants: [
      '200',
      '300',
      'regular',
      '500',
      '600',
      '700',
      '800',
      '900',
      '200italic',
      '300italic',
      'italic',
      '500italic',
      '600italic',
      '700italic',
      '800italic',
      '900italic',
    ],
    subsets: [
      'cyrillic',
      'cyrillic-ext',
      'greek',
      'greek-ext',
      'latin',
      'latin-ext',
      'vietnamese',
    ],
  },
  {
    family: 'Space Mono',
    variants: ['regular', 'italic', '700', '700italic'],
    subsets: ['latin', 'latin-ext', 'vietnamese'],
  },
  {
    family: 'Spectral',
    variants: [
      '200',
      '200italic',
      '300',
      '300italic',
      'regular',
      'italic',
      '500',
      '500italic',
      '600',
      '600italic',
      '700',
      '700italic',
      '800',
      '800italic',
    ],
    subsets: ['cyrillic', 'latin', 'latin-ext', 'vietnamese'],
  },
  {
    family: 'Work Sans',
    variants: [
      '100',
      '200',
      '300',
      'regular',
      '500',
      '600',
      '700',
      '800',
      '900',
      '100italic',
      '200italic',
      '300italic',
      'italic',
      '500italic',
      '600italic',
      '700italic',
      '800italic',
      '900italic',
    ],
    subsets: ['latin', 'latin-ext', 'vietnamese'],
  },
];
