/**
 * This file is generated by Jux. For more information on how to use this file, visit https://jux.io/docs
 */

export const core = {
  $description: 'Core tokens',
  border: {
    $description: 'Border tokens',
  },
  typography: {
    $description: 'Typography tokens',
  },
  fontFamily: {
    $description: 'Font family tokens',
    asd: {
      $value: 'BioRhyme, serif',
      $description: '',
    },
  },
  dimension: {
    $description: 'Dimension tokens',
  },
  color: {
    $description: 'Color tokens',
    yellows: {
      '200': {
        $value: 'rgba(255 238 194 / 100%)',
      },
      '500': {
        $value: 'rgba(255 203 71 / 100%)',
      },
      '800': {
        $value: 'rgba(138 103 15 / 100%)',
      },
    },
    pinks: {
      '200': {
        $value: 'rgba(255 214 218 / 100%)',
      },
      '500': {
        $value: 'rgba(255 92 108 / 100%)',
      },
      '800': {
        $value: 'rgba(143 20 32 / 100%)',
      },
    },
    purples: {
      '100': {
        $value: 'rgba(249 242 253 / 100%)',
      },
      '200': {
        $value: 'rgba(243 225 254 / 100%)',
      },
      '300': {
        $value: 'rgba(202 131 252 / 100%)',
      },
      '500': {
        $value: 'rgba(157 10 255 / 100%)',
      },
      '700': {
        $value: 'rgba(106 9 170 / 100%)',
      },
      '800': {
        $value: 'rgba(65 11 101 / 100%)',
      },
      '900': {
        $value: 'rgba(49 5 76 / 100%)',
      },
    },
    blues: {
      '100': {
        $value: 'rgba(242 246 253 / 100%)',
      },
      '200': {
        $value: 'rgba(229 242 255 / 100%)',
      },
      '300': {
        $value: 'rgba(130 201 252 / 100%)',
      },
      '500': {
        $value: 'rgba(5 143 242 / 100%)',
      },
      '700': {
        $value: 'rgba(10 75 205 / 100%)',
      },
      '800': {
        $value: 'rgba(10 31 92 / 100%)',
      },
      '900': {
        $value: 'rgba(6 25 71 / 100%)',
      },
    },
    greys: {
      '0': {
        $value: 'rgba(255 255 255 / 100%)',
      },
      '50': {
        $value: 'rgba(247 247 247 / 100%)',
      },
      '100': {
        $value: 'rgba(242 242 242 / 100%)',
      },
      '150': {
        $value: 'rgba(235 235 235 / 100%)',
      },
      '200': {
        $value: 'rgba(224 224 224 / 100%)',
      },
      '300': {
        $value: 'rgba(189 189 189 / 100%)',
      },
      '400': {
        $value: 'rgba(158 158 158 / 100%)',
      },
      '500': {
        $value: 'rgba(97 97 97 / 100%)',
      },
      '600': {
        $value: 'rgba(71 71 71 / 100%)',
      },
      '650': {
        $value: 'rgba(48 48 48 / 100%)',
      },
      '700': {
        $value: 'rgba(39 39 39 / 100%)',
      },
      '800': {
        $value: 'rgba(31 31 31 / 100%)',
      },
      '900': {
        $value: 'rgba(20 20 20 / 100%)',
      },
      '1000': {
        $description: '',
        $value: 'rgba(10 10 10 / 100%)',
      },
      alfa_30: {
        $value: 'rgba(0 0 0 / 30%)',
      },
      alfa_20: {
        $value: 'rgba(0 0 0 / 20%)',
      },
      alfa_10: {
        $value: 'rgba(0 0 0 / 10%)',
      },
    },
  },
};
