/**
 * This file is generated by Jux. For more information on how to use this file, visit https://jux.io/docs
 */

export const light = {
  color: {
    $description: 'Color tokens',
    text_blue: {
      '0': {
        $value: '{core.color.blues.500}',
      },
      m2: {
        $value: '{core.color.blues.200}',
      },
      m1: {
        $value: '{core.color.blues.300}',
      },
      p1: {
        $value: '{core.color.blues.700}',
      },
      p2: {
        $value: '{core.color.blues.800}',
      },
      p3: {
        $value: '{core.color.blues.900}',
      },
      m3: {
        $value: '{core.color.blues.100}',
      },
    },
    border_blue: {
      '0': {
        $value: '{core.color.blues.500}',
      },
      m3: {
        $value: '{core.color.blues.100}',
      },
      m2: {
        $value: '{core.color.blues.200}',
      },
      m1: {
        $value: '{core.color.blues.300}',
      },
      p1: {
        $value: '{core.color.blues.700}',
      },
      p2: {
        $value: '{core.color.blues.800}',
      },
      p3: {
        $value: '{core.color.blues.900}',
      },
    },
    fill_blue: {
      '0': {
        $value: '{core.color.blues.500}',
      },
      m3: {
        $value: '{core.color.blues.100}',
      },
      m2: {
        $value: '{core.color.blues.200}',
      },
      m1: {
        $value: '{core.color.blues.300}',
      },
      p1: {
        $value: '{core.color.blues.700}',
      },
      p2: {
        $value: '{core.color.blues.800}',
      },
      p3: {
        $value: '{core.color.blues.900}',
      },
    },
    fill_base: {
      '0': {
        $value: '{core.color.greys.400}',
      },
      p5: {
        $description: '',
        $value: '{core.color.greys.1000}',
      },
      p3: {
        $value: '{core.color.greys.800}',
      },
      p4: {
        $description: '',
        $value: '{core.color.greys.900}',
      },
      m5: {
        $value: '{core.color.greys.0}',
      },
      m4: {
        $value: '{core.color.greys.50}',
      },
      m3: {
        $value: '{core.color.greys.100}',
      },
      m2: {
        $value: '{core.color.greys.150}',
      },
      m1: {
        $value: '{core.color.greys.200}',
      },
      p1: {
        $value: '{core.color.greys.500}',
      },
      p2: {
        $value: '{core.color.greys.700}',
      },
    },
    text_base: {
      '0': {
        $value: '{core.color.greys.400}',
      },
      m5: {
        $value: '{core.color.greys.0}',
      },
      m1: {
        $value: '{core.color.greys.200}',
      },
      p1: {
        $value: '{core.color.greys.500}',
      },
      p2: {
        $value: '{core.color.greys.700}',
      },
      p3: {
        $value: '{core.color.greys.800}',
      },
    },
    border_base: {
      '0': {
        $value: '{core.color.greys.400}',
      },
      m3: {
        $value: '{core.color.greys.100}',
      },
      m2: {
        $value: '{core.color.greys.150}',
      },
      m1: {
        $value: '{core.color.greys.200}',
      },
      p1: {
        $value: '{core.color.greys.500}',
      },
      p3: {
        $value: '{core.color.greys.800}',
      },
    },
    fill_yellow: {
      '0': {
        $value: '{core.color.yellows.500}',
      },
      m2: {
        $value: '{core.color.yellows.200}',
      },
      p2: {
        $value: '{core.color.yellows.800}',
      },
    },
    fill_pink: {
      '0': {
        $value: '{core.color.pinks.500}',
      },
      m2: {
        $value: '{core.color.pinks.200}',
      },
      p2: {
        $value: '{core.color.pinks.800}',
      },
    },
    text_purple: {
      '0': {
        $value: '{core.color.purples.500}',
      },
      m3: {
        $value: '{core.color.purples.100}',
      },
      m2: {
        $value: '{core.color.purples.200}',
      },
      m1: {
        $value: '{core.color.purples.300}',
      },
      p1: {
        $value: '{core.color.purples.700}',
      },
      p2: {
        $value: '{core.color.purples.800}',
      },
      p3: {
        $value: '{core.color.purples.900}',
      },
    },
    fill_purple: {
      '0': {
        $value: '{core.color.purples.500}',
      },
      m3: {
        $value: '{core.color.purples.100}',
      },
      m2: {
        $value: '{core.color.purples.200}',
      },
      m1: {
        $value: '{core.color.purples.300}',
      },
      p1: {
        $value: '{core.color.purples.700}',
      },
      p2: {
        $value: '{core.color.purples.800}',
      },
      p3: {
        $value: '{core.color.purples.900}',
      },
    },
  },
  border: {
    $description: 'Border tokens',
  },
  typography: {
    $description: 'Typography tokens',
  },
  fontFamily: {
    $description: 'Font family tokens',
  },
  dimension: {
    $description: 'Dimension tokens',
  },
};
