/**
 * This file is generated by Jux. For more information on how to use this file, visit https://jux.io/docs
 */
import { defineTokenSet } from '@juxio/cli';

export const core = defineTokenSet({
  color: {
    $description: 'Color tokens',
  },
  border: {
    $description: 'Border tokens',
  },
  dimension: {
    $description: 'Dimension tokens',
  },
  fontFamily: {
    $description: 'Font family tokens',
  },
  typography: {
    $description: 'Typography tokens',
  },
  $description: 'Core tokens',
});
