/**
 * This file is generated by Jux. For more information on how to use this file, visit https://jux.io/docs
 */
import { defineTokenSet } from '@juxio/cli';

export const light = defineTokenSet({
  color: {
    core: {
      grays_0: {
        $value: 'rgba(255 255 255 / 100%)',
        $description: '',
      },
      blues_100: {
        $value: 'rgba(230 242 250 / 100%)',
        $description: '',
      },
      blues_200: {
        $value: 'rgba(217 239 255 / 100%)',
        $description: '',
      },
      blues_500: {
        $value: 'rgba(5 143 242 / 100%)',
        $description: '',
      },
      grays_100: {
        $value: 'rgba(242 242 242 / 100%)',
        $description: '',
      },
      grays_150: {
        $value: 'rgba(235 235 235 / 100%)',
        $description: '',
      },
      grays_200: {
        $value: 'rgba(224 224 224 / 100%)',
        $description: '',
      },
      grays_300: {
        $value: 'rgba(189 189 189 / 100%)',
        $description: '',
      },
      grays_400: {
        $value: 'rgba(158 158 158 / 100%)',
        $description: '',
      },
      grays_500: {
        $value: 'rgba(97 97 97 / 100%)',
        $description: '',
      },
      grays_600: {
        $value: 'rgba(71 71 71 / 100%)',
        $description: '',
      },
      grays_650: {
        $value: 'rgba(48 48 48 / 100%)',
        $description: '',
      },
      grays_700: {
        $value: 'rgba(39 39 39 / 100%)',
        $description: '',
      },
      grays_750: {
        $value: 'rgba(33 33 33 / 100%)',
        $description: '',
      },
      grays_800: {
        $value: 'rgba(26 26 26 / 100%)',
        $description: '',
      },
      grays_900: {
        $value: 'rgba(20 20 20 / 100%)',
        $description: '',
      },
      pinks_200: {
        $value: 'rgba(255 214 218 / 100%)',
        $description: '',
      },
      pinks_300: {
        $value: 'rgba(255 153 163 / 100%)',
        $description: '',
      },
      pinks_500: {
        $value: 'rgba(255 92 108 / 100%)',
        $description: '',
      },
      grays_1000: {
        $value: 'rgba(0 0 0 / 100%)',
        $description: 'only used in banners',
      },
      purples_200: {
        $value: 'rgba(222 173 255 / 100%)',
        $description: '',
      },
      purples_300: {
        $value: 'rgba(198 112 255 / 100%)',
        $description: '',
      },
      purples_500: {
        $value: 'rgba(157 10 255 / 100%)',
        $description: '',
      },
      yellows_200: {
        $value: 'rgba(255 238 194 / 100%)',
        $description: '',
      },
      yellows_300: {
        $value: 'rgba(255 220 133 / 100%)',
        $description: '',
      },
      yellows_500: {
        $value: 'rgba(255 203 71 / 100%)',
        $description: '',
      },
      $description:
        'Core tokens are used as the base palette of global visual options in any token type.They are usually primitive tokens, pointing to a concrete value.\nCore folders can’t be edited or deleted.',
    },
    default: {
      $description: 'Default',
    },
    semantic: {
      fill_base_2: {
        $value: 'rgba(55 45 107 / 100%)',
        $description: '',
      },
      fill_base_3: {
        $value: '{light.color.core.grays_800}',
        $description: '',
      },
      $description:
        'Semantic tokens are used for representing broad purpose or intent which remains true when switching between token sets.They are always alias tokens, usually pointing to core tokens.\nSemantic folders can’t be edited or deleted.',
    },
    specific: {
      $description:
        'Specific tokens are used for targeting individual components or sets of components of the same kind.They are always alias tokens, either pointing to core or alias tokens.\nSpecific folders can’t be edited or deleted.',
    },
    $description: 'Color tokens',
  },
  border: {
    core: {
      $description:
        'Core tokens are used as the base palette of global visual options in any token type.They are usually primitive tokens, pointing to a concrete value.\nCore folders can’t be edited or deleted.',
    },
    default: {
      $description: 'Default',
    },
    semantic: {
      $description:
        'Semantic tokens are used for representing broad purpose or intent which remains true when switching between token sets.They are always alias tokens, usually pointing to core tokens.\nSemantic folders can’t be edited or deleted.',
    },
    specific: {
      $description:
        'Specific tokens are used for targeting individual components or sets of components of the same kind.They are always alias tokens, either pointing to core or alias tokens.\nSpecific folders can’t be edited or deleted.',
    },
    $description: 'Border tokens',
  },
  dimension: {
    core: {
      size_m: {
        $value: '24px',
        $description: '',
      },
      size_lg: {
        $value: '40px',
        $description: '',
      },
      size_ml: {
        $value: '32px',
        $description: '',
      },
      size_sm: {
        $value: '16px',
        $description: '',
      },
      size_xl: {
        $value: '52px',
        $description: '',
      },
      size_xs: {
        $value: '8px',
        $description: '',
      },
      radius_l: {
        $value: '12px',
        $description: '',
      },
      radius_m: {
        $value: '8px',
        $description: '',
      },
      radius_s: {
        $value: '4px',
        $description: '',
      },
      size_2lg: {
        $value: '48px',
        $description: 'new ',
      },
      size_2xl: {
        $value: '64px',
        $description: '',
      },
      size_3xl: {
        $value: '128px',
        $description: '',
      },
      space_lg: {
        $value: '16px',
        $description: '',
      },
      space_md: {
        $value: '8px',
        $description: '',
      },
      space_ml: {
        $value: '12px',
        $description: '',
      },
      space_sm: {
        $value: '4px',
        $description: '',
      },
      space_xl: {
        $value: '24px',
        $description: '',
      },
      space_xs: {
        $value: '2px',
        $description: '',
      },
      space_2xl: {
        $value: '32px',
        $description: '',
      },
      space_3xl: {
        $value: '48px',
        $description: '',
      },
      $description:
        'Core tokens are used as the base palette of global visual options in any token type.They are usually primitive tokens, pointing to a concrete value.\nCore folders can’t be edited or deleted.',
      radius_round: {
        $value: '9999px',
        $description: '',
      },
      padding_sides: {
        $value: '2.5rem',
        $description: '',
      },
    },
    default: {
      $description: 'Default',
    },
    semantic: {
      $description:
        'Semantic tokens are used for representing broad purpose or intent which remains true when switching between token sets.They are always alias tokens, usually pointing to core tokens.\nSemantic folders can’t be edited or deleted.',
      small_border_radius: {
        $value: '{light.dimension.core.space_xs}',
        $description: '',
      },
    },
    specific: {
      button_4: {
        $value: '4px',
        $description: '',
      },
      $description:
        'Specific tokens are used for targeting individual components or sets of components of the same kind.They are always alias tokens, either pointing to core or alias tokens.\nSpecific folders can’t be edited or deleted.',
      button_radius: {
        $value: '{light.dimension.semantic.small_border_radius}',
        $description: '',
      },
    },
    $description: 'Dimension tokens',
  },
  fontFamily: {
    core: {
      base: {
        $value: 'Inter, sans-serif',
        $description: '',
      },
      titles: {
        $value: 'Libre Franklin, sans-serif',
        $description: '',
      },
      $description:
        'Core tokens are used as the base palette of global visual options in any token type.They are usually primitive tokens, pointing to a concrete value.\nCore folders can’t be edited or deleted.',
    },
    default: {
      $description: 'Default',
    },
    semantic: {
      $description:
        'Semantic tokens are used for representing broad purpose or intent which remains true when switching between token sets.They are always alias tokens, usually pointing to core tokens.\nSemantic folders can’t be edited or deleted.',
    },
    specific: {
      $description:
        'Specific tokens are used for targeting individual components or sets of components of the same kind.They are always alias tokens, either pointing to core or alias tokens.\nSpecific folders can’t be edited or deleted.',
    },
    $description: 'Font family tokens',
  },
  typography: {
    core: {
      '12_bold': {
        $value: {
          fontSize: '12px',
          fontFamily: '{light.fontFamily.core.base}',
          fontWeight: '700',
          lineHeight: '16px',
          letterSpacing: '',
        },
        $description: '',
      },
      '14_bold': {
        $value: {
          fontSize: '14px',
          fontFamily: '{light.fontFamily.core.base}',
          fontWeight: '700',
          lineHeight: '20px',
          letterSpacing: '1%',
        },
        $description: '',
      },
      '14_semi': {
        $value: {
          fontSize: '14px',
          fontFamily: '{light.fontFamily.core.base}',
          fontWeight: '600',
          lineHeight: '20px',
          letterSpacing: '1%',
        },
        $description: '',
      },
      '11_medium': {
        $value: {
          fontSize: '11px',
          fontFamily: '{light.fontFamily.core.base}',
          fontWeight: '500',
          lineHeight: '16px',
          letterSpacing: '',
        },
        $description: '',
      },
      '12_medium': {
        $value: {
          fontSize: '12px',
          fontFamily: '{light.fontFamily.core.base}',
          fontWeight: '500',
          lineHeight: '16px',
          letterSpacing: '',
        },
        $description: '',
      },
      '11_regular': {
        $value: {
          fontSize: '11px',
          fontFamily: '{light.fontFamily.core.base}',
          fontWeight: '400',
          lineHeight: '14px',
          letterSpacing: '',
        },
        $description: '',
      },
      '12_regular': {
        $value: {
          fontSize: '12px',
          fontFamily: '{light.fontFamily.core.base}',
          fontWeight: '400',
          lineHeight: '16px',
          letterSpacing: '',
        },
        $description: '',
      },
      '14_regular': {
        $value: {
          fontSize: '14px',
          fontFamily: '{light.fontFamily.core.base}',
          fontWeight: '400',
          lineHeight: '20px',
          letterSpacing: '',
        },
        $description: '',
      },
      '16_regular': {
        $value: {
          fontSize: '16px',
          fontFamily: '{light.fontFamily.core.base}',
          fontWeight: '400',
          lineHeight: '150%',
          letterSpacing: '',
        },
        $description: '',
      },
      '28_regular': {
        $value: {
          fontSize: '28px',
          fontFamily: '{light.fontFamily.core.base}',
          fontWeight: '400',
          lineHeight: '100px',
          letterSpacing: '',
        },
        $description: '',
      },
      $description:
        'Core tokens are used as the base palette of global visual options in any token type.They are usually primitive tokens, pointing to a concrete value.\nCore folders can’t be edited or deleted.',
    },
    default: {
      $description: 'Default',
    },
    semantic: {
      header_1: {
        $value: '{light.typography.core.28_regular}',
        $description: '',
      },
      header_2: {
        $value: '{light.typography.core.16_regular}',
        $description: '',
      },
      body_bold: {
        $value: '{light.typography.core.14_bold}',
        $description: '',
      },
      body_semi: {
        $value: '{light.typography.core.14_semi}',
        $description: '',
      },
      $description:
        'Semantic tokens are used for representing broad purpose or intent which remains true when switching between token sets.They are always alias tokens, usually pointing to core tokens.\nSemantic folders can’t be edited or deleted.',
      body_regular: {
        $value: '{light.typography.core.14_regular}',
        $description: '',
      },
      'label-small-bold': {
        $value: '{light.typography.core.12_bold}',
        $description: '',
      },
      'label-small-medium': {
        $value: '{light.typography.core.12_medium}',
        $description: '',
      },
      'label-small-regular': {
        $value: '{light.typography.core.12_regular}',
        $description: '',
      },
      'helper-small-regular': {
        $value: '{light.typography.core.12_regular}',
        $description: '',
      },
      'label-x-small-medium': {
        $value: '{light.typography.core.11_medium}',
        $description: '',
      },
      'label-x-small-regular': {
        $value: '{light.typography.core.11_regular}',
        $description: '',
      },
    },
    specific: {
      $description:
        'Specific tokens are used for targeting individual components or sets of components of the same kind.They are always alias tokens, either pointing to core or alias tokens.\nSpecific folders can’t be edited or deleted.',
    },
    $description: 'Typography tokens',
  },
});
