name: 'write env file'
description: 'Sets up env file with api url for CLI'

runs:
  using: composite
  steps:
    - name: Create env file
      shell: bash
      run: |
        echo "API_SERVER=${{ vars.API_SERVER }}" > packages/cli/.env
        echo "CLIENT_ID=${{ vars.CLIENT_ID }}" > packages/cli/.env
        echo "AUTH_DOMAIN=${{ vars.AUTH_DOMAIN }}" > packages/cli/.env
        echo "API_AUDIENCE=${{ vars.API_AUDIENCE }}" > packages/cli/.env