name: Release dev version

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release dev version
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm and dependencies
        uses: ./.github/common-actions/install

      - name: Create env file for CLI
        shell: bash
        run: |
          echo "API_SERVER=${{ vars.API_SERVER }}" > packages/cli/.env
          echo "CLIENT_ID=${{ vars.CLIENT_ID }}" > packages/cli/.env
          echo "AUTH_DOMAIN=${{ vars.AUTH_DOMAIN }}" > packages/cli/.env
          echo "API_AUDIENCE=${{ vars.API_AUDIENCE }}" > packages/cli/.env

      - name: Build packages
        run: pnpm build

      - name: Login to NPM
        run: printf "registry=https://${{ vars.NPM_REGISTRY }}\n//${{ vars.NPM_REGISTRY }}/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Release to dev tag
        run: pnpm release:dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}