name: Release

on:
  push:
    paths:
      - '.changeset/**'
      - 'packages/**'
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/common-actions/install

      - name: Create env file for CLI
        run: |
          echo "API_SERVER=${{ vars.API_SERVER }}" >> packages/core/.env
          echo "CLIENT_ID=${{ vars.CLIENT_ID }}" >> packages/core/.env
          echo "AUTH_DOMAIN=${{ vars.AUTH_DOMAIN }}" >> packages/core/.env
          echo "API_AUDIENCE=${{ vars.API_AUDIENCE }}" >> packages/core/.env

      - name: Build packages
        run: pnpm build

      - name: Login to NPM
        run: printf "registry=https://${{ vars.NPM_REGISTRY }}\n//${{ vars.NPM_REGISTRY }}/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Create Release PR or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
          version: pnpm run version
          commit: "chore: new release"
          title: "chore: new release candidate"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}