name: Release dev version

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release dev version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and install
        uses: ./.github/common-actions/install

      - name: Release to dev tag
        run: |
          pnpm changeset version --snapshot dev
          pnpm changeset publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}