name: Release dev version

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release dev version
    environment: ${{ inputs.env }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/common-actions/install

      - name: Login to NPM
        run: echo "//${{ vars.NPM_REGISTRY }}/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Release to dev tag
        run: |
          pnpm changeset version --snapshot dev
          pnpm changeset publish --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}