name: Tests

on:
  pull_request:
    paths:
      - '.changeset/**'
      - 'packages/**'
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    name: Test packages
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/common-actions/install

      - name: Create env file for CLI
        run: |
          echo "API_SERVER=${{ vars.API_SERVER }}" >> packages/core/.env
          echo "CLIENT_ID=${{ vars.CLIENT_ID }}" >> packages/core/.env
          echo "AUTH_DOMAIN=${{ vars.AUTH_DOMAIN }}" >> packages/core/.env
          echo "API_AUDIENCE=${{ vars.API_AUDIENCE }}" >> packages/core/.env

      - name: Build packages
        run: pnpm build

      - name: Test packages
        run: pnpm test
