name: Tests

on:
  pull_request:
    paths:
      - 'website/**'
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    name: Test packages
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/common-actions/install

      - name: Build website
        run: pnpm build:website
